abbr -a -- gco     'git checkout'
abbr -a -- gp      'git pull'
abbr -a -- gf      'git fetch --all'
abbr -a -- gcu     '~/.local/bin/git-cleanup.sh'
abbr -a -- gbom    '~/.local/bin/git-base-on-master.sh'
abbr -a -- vi      'vim'
abbr -a -- dsdev   'devspace dev'
abbr -a -- dscs    'devspace run codestyle'
abbr -a -- dslogs  'devspace run mylogs'
abbr -a -- dscu    'devspace run composer update'
abbr -a -- dstst   'devspace run tests'
abbr -a -- dsapi   'devspace run api-tests'
abbr -a -- docker-compose 'docker compose'
