abbr -a -- gco            'git checkout'
abbr -a -- gcu            '~/.local/bin/git-cleanup.sh'
abbr -a -- gbom           '~/.local/bin/git-base-on-master.sh'
abbr -a -- vi             'vim'
abbr -a -- docker-compose 'docker compose'
